### ISSUE TITLE
直接拉取最新的代码 启动不了

### ISSUE THREAD

**Issue by Fearyao** [lqsong/admin-element-vue#10]
分支 vite.ts

```
D:\learn>git clone -b vite.ts  https://github.com/lqsong/admin-element-vue.git
Cloning into 'admin-element-vue'...
remote: Enumerating objects: 476, done.
remote: Counting objects: 100% (476/476), done.
remote: Compressing objects: 100% (358/358), done.
remote: Total 1314 (delta 155), reused 391 (delta 83), pack-reused 838
Receiving objects: 100% (1314/1314), 837.89 KiB | 535.00 KiB/s, done.
Resolving deltas: 100% (549/549), done.

D:\learn>cd admin-element-vue

D:\learn\admin-element-vue>yarn
yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
warning @ckeditor/ckeditor5-build-decoupled-document > webpack-cli > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @ckeditor/ckeditor5-build-decoupled-document > webpack-cli > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning Resolution field "@babel/standalone@7.13.9" is incompatible with requested version "@babel/standalone@^7.13.12"
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning vue-jest > extract-from-css > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@ckeditor/ckeditor5-build-decoupled-document > webpack-cli@3.3.12" has unmet peer dependency "webpack@4.x.x".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
success Saved lockfile.
Done in 17.45s.

D:\learn\admin-element-vue>yarn dev
yarn run v1.22.10
$ vite
failed to load config from D:\learn\admin-element-vue\vite.config.ts
error when starting dev server:
Error: ENOENT: no such file or directory, scandir 'D:\learn\admin-element-vue\src\components\IconSvg\src\assets\iconsvg'
    at readdirSync (fs.js:1021:3)
    at findSvgFile (D:\learn\admin-element-vue\vite.config.ts:264:46)
    at vitePluginIconSvg (D:\learn\admin-element-vue\vite.config.ts:293:15)
    at D:\learn\admin-element-vue\vite.config.ts:315:5
    at loadConfigFromFile (D:\learn\admin-element-vue\node_modules\vite\dist\node\chunks\dep-66eb515d.js:46271:59)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async resolveConfig (D:\learn\admin-element-vue\node_modules\vite\dist\node\chunks\dep-66eb515d.js:45889:28)
    at async createServer (D:\learn\admin-element-vue\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69132:20)
    at async CAC.<anonymous> (D:\learn\admin-element-vue\node_modules\vite\dist\node\cli.js:14037:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lqsong** [comment]
什么系统？

**Comment by lqsong** [comment]
`vite`版本问题造成的错误，`vite@2.1.2`默认`vite.config.ts`加载插件`path.resolve(__dirname)`是相对`vite.config.ts`，现在最新版`vite@2.1.5` 加载插件`path.resolve(__dirname)`相对的是插件文件本身，你现在目前可以指定安装`vite@2.1.2`版本：`yarn add vite@2.1.2 -D`，或者等待项目修复升级。

**Comment by lqsong** [comment]
已修复：https://github.com/lqsong/admin-element-vue/commit/d4cb5e860e37a13b5c58de468c573d113c08b7b1
